services:
  - type: web
    name: vibecode-backend
    runtime: python
    repo: https://github.com/feranmiabiola1002/vibecode
    branch: main
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: INFO
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app -w 1
    healthCheckPath: /
    autoDeploy: true
